/* CVS $Id: $ */
package org.wymiwyg.bundleloader.vocabulary; 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;
 
/**
 * Vocabulary definitions from http://framework.wymiwyg.org/ontology 
 * @author Auto-generated by schemagen on 09 Mrz 2008 19:46 
 */
public class BUNDLES {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://framework.wymiwyg.org/ontology#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final DatatypeProperty location = m_model.createDatatypeProperty( "http://framework.wymiwyg.org/ontology#location" );
    
    public static final OntClass Bundle = m_model.createClass( "http://framework.wymiwyg.org/ontology#Bundle" );
    
}
